In [1]:
import pandas as pd
import numpy as np

# Load Data

In [2]:
data_proc = pd.read_csv('/content/Absenteeism_preprocessed.csv')
data_proc

reason_1  reason_2  reason_3  reason_4  Month Values  Day of the week  \
0           0         0         0         1             7                1   
1           0         0         0         0             7                1   
2           0         0         0         1             7                2   
3           1         0         0         0             7                3   
4           0         0         0         1             7                3   
..        ...       ...       ...       ...           ...              ...   
695         1         0         0         0             5                2   
696         1         0         0         0             5                2   
697         1         0         0         0             5                3   
698         0         0         0         1             5                3   
699         0         0         0         1             5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 15 columns]

# Creating targets

In [3]:
data_proc['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_proc['Absenteeism Time in Hours'] >
                   data_proc['Absenteeism Time in Hours'].median(), 1, 0)

In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_proc['Excessive Absenteeism'] = targets

In [7]:
data_proc.head()

reason_1  reason_2  reason_3  reason_4  Month Values  Day of the week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [8]:
targets.sum() / targets.shape[0]

0.45571428571428574

# Checkpoint

In [9]:
data_with_targets = data_proc.drop(['Absenteeism Time in Hours', 'Day of the week', 'Daily Work Load Average', 'Distance to Work'], axis= 1)

In [10]:
data_with_targets is data_proc

False

In [11]:
data_with_targets.head()

reason_1  reason_2  reason_3  reason_4  Month Values  \
0         0         0         0         1             7   
1         0         0         0         0             7   
2         0         0         0         1             7   
3         1         0         0         0             7   
4         0         0         0         1             7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [12]:
data_with_targets.shape

(700, 12)

In [13]:
data_with_targets.iloc[:, 0:14]

reason_1  reason_2  reason_3  reason_4  Month Values  \
0           0         0         0         1             7   
1           0         0         0         0             7   
2           0         0         0         1             7   
3           1         0         0         0             7   
4           0         0         0         1             7   
..        ...       ...       ...       ...           ...   
695         1         0         0         0             5   
696         1         0         0         0             5   
697         1         0         0         0             5   
698         0         0         0         1             5   
699         0         0         0         1             5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [14]:
data_with_targets.iloc[:, :-1]

reason_1  reason_2  reason_3  reason_4  Month Values  \
0           0         0         0         1             7   
1           0         0         0         0             7   
2           0         0         0         1             7   
3           1         0         0         0             7   
4           0         0         0         1             7   
..        ...       ...       ...       ...           ...   
695         1         0         0         0             5   
696         1         0         0         0             5   
697         1         0         0         0             5   
698         0         0         0         1             5   
699         0         0         0         1             5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [15]:
# Se omite la última colomna del df. Al no indicar el principio de y como último valor -1 se omite la última columna

unscaled_inputs = data_with_targets.iloc[:, :-1]
unscaled_inputs.head()

reason_1  reason_2  reason_3  reason_4  Month Values  \
0         0         0         0         1             7   
1         0         0         0         0             7   
2         0         0         0         1             7   
3         1         0         0         0             7   
4         0         0         0         1             7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                     289   33               30          0         2     1  
1                     118   50               31          0         1     0  
2                     179   38               31          0         0     0  
3                     279   39               24          0         2     0  
4                     289   33               30          0         2     1

In [16]:
#!pip install ez_setup

In [17]:
#from sklearn.preprocessing import StandardScaler

In [18]:
#absenteeism_scaler = StandardScaler()

In [19]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
  def __init__(self, columns):
    self.scaler = StandardScaler()
    self.columns = columns
    self.mean_ = None
    self.var_ = None

  def fit(self, X, y=None):
    self.scaler.fit(X[self.columns], y)
    self.mean_ = np.mean(X[self.columns])
    self.var_ = np.var(X[self.columns])

    return self

  def transform(self, X, y=None, copy=None):
    init_col_order = X.columns
    X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
    X_not_scaled = X.loc[:, X.columns.isin(self.columns)]

    return pd.concat([X_scaled], axis=1)[init_col_order]


In [20]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [21]:
columns_to_scale = ['Month Values', 'Transportation Expense',
       'Age', 'Body Mass Index',  'Children', 'Pets']

In [22]:
unscaled_inputs_copy = unscaled_inputs.copy()

In [23]:
unscaled_inputs_copy = unscaled_inputs.drop(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Education'], axis=1)

In [24]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [25]:
scaled_inputs = absenteeism_scaler.fit_transform(unscaled_inputs_copy)

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


In [26]:
#scaled_inputs = absenteeism_scaler.transform(unscaled_inputs_copy)
scaled_inputs

Month Values  Transportation Expense       Age  Body Mass Index  \
0        0.182726                1.005844 -0.536062         0.767431   
1        0.182726               -1.574681  2.130803         1.002633   
2        0.182726               -0.654143  0.248310         1.002633   
3        0.182726                0.854936  0.405184        -0.643782   
4        0.182726                1.005844 -0.536062         0.767431   
..            ...                     ...       ...              ...   
695     -0.388293               -0.654143  0.562059        -1.114186   
696     -0.388293                0.040034 -1.320435        -0.643782   
697     -0.388293                1.624567 -1.320435        -0.408580   
698     -0.388293                0.190942 -0.692937        -0.408580   
699     -0.388293                1.036026  0.562059        -0.408580   

     Children      Pets  
0    0.880469  0.268487  
1   -0.019280 -0.589690  
2   -0.919030 -0.589690  
3    0.880469 -0.589690  
4    0.880469  0.268487  
..        ...       ...  
695  0.880469 -0.589690  
696 -0.019280  1.126663  
697 -0.919030 -0.589690  
698 -0.919030 -0.589690  
699 -0.019280  0.268487  

[700 rows x 6 columns]

In [27]:
reason_1 = unscaled_inputs['reason_1']
reason_2 = unscaled_inputs['reason_2']
reason_3 = unscaled_inputs['reason_3']
reason_4 = unscaled_inputs['reason_4']
Education = unscaled_inputs['Education']

In [28]:
scaled_inputs = pd.concat([scaled_inputs, reason_1, reason_2, reason_3, reason_4, Education], axis=1)
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [29]:
reorder_columns = ['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets']

scaled_inputs = scaled_inputs[reorder_columns]

In [30]:
scaled_inputs

reason_1  reason_2  reason_3  reason_4  Month Values  \
0           0         0         0         1      0.182726   
1           0         0         0         0      0.182726   
2           0         0         0         1      0.182726   
3           1         0         0         0      0.182726   
4           0         0         0         1      0.182726   
..        ...       ...       ...       ...           ...   
695         1         0         0         0     -0.388293   
696         1         0         0         0     -0.388293   
697         1         0         0         0     -0.388293   
698         0         0         0         1     -0.388293   
699         0         0         0         1     -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [31]:
scaled_inputs.shape

(700, 11)

# Split the data into train & test and shuffle

###Import the relevant module

In [32]:
from sklearn.model_selection import train_test_split

### Split

In [33]:
train_test_split(scaled_inputs, targets)

[     reason_1  reason_2  reason_3  reason_4  Month Values  \
 339         1         0         0         0      1.610276   
 409         0         0         0         1     -0.959313   
 490         0         0         0         1      0.468236   
 265         0         0         0         1      0.468236   
 277         0         0         0         0      0.753746   
 ..        ...       ...       ...       ...           ...   
 535         0         0         0         1      1.324766   
 192         0         0         0         1     -0.673803   
 167         1         0         0         0     -0.959313   
 453         0         0         0         1     -0.102784   
 402         0         0         0         1     -0.959313   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 339                0.040034 -1.320435        -0.643782          0 -0.019280   
 409                1.005844 -0.536062         0.767431          0  0.880469   
 490          

In [34]:
# Se hace la división de las observaciones para prueba y entrenamiento del modelo.
# por default se asigna 75% de las observaciones para entrenar el modelo y 25% de las observaciones para testeo.

x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [35]:
print( x_train.shape, y_train.shape)

(560, 11) (560,)


In [36]:
print( y_test.shape, x_test.shape)

(140,) (140, 11)


# Logistic regression with sklearn

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### training the model

In [38]:
reg  = LogisticRegression()

In [39]:
reg.fit(x_train,y_train)

LogisticRegression()

In [40]:
reg.score(x_train, y_train)

0.7732142857142857

# Manually check the accuracy

In [41]:
# muestra un array con las predicciones de nuestro modelo

model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [42]:
# muestra los targets

y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [43]:
# result True, si hay un match entre dos df

model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [44]:
# numero de total de elementos que coinciden
np.sum(model_outputs == y_train)

433

In [45]:
model_outputs.shape[0]

560

In [46]:
np.sum(model_outputs == y_train)  / model_outputs.shape[0]

0.7732142857142857

# Finding the intercept and coefficients

In [47]:
reg.intercept_

array([-1.6474549])

In [48]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [49]:
feature_name = unscaled_inputs.columns.values

In [50]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 reason_1     2.800197
1                 reason_2     0.951884
2                 reason_3     3.115553
3                 reason_4     0.839001
4             Month Values     0.158930
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396

In [51]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.647455
1                 reason_1     2.800197
2                 reason_2     0.951884
3                 reason_3     3.115553
4                 reason_4     0.839001
5             Month Values     0.158930
6   Transportation Expense     0.605284
7                      Age    -0.169891
8          Body Mass Index     0.279811
9                Education    -0.210533
10                Children     0.348262
11                    Pets    -0.277396

# Interpretación de la regresion logistica

In [52]:
'''
Mientras más cerca este de cero el coeficiente, mas pequeño es el peso.
Mientras más lejos del cero esté, sin importar si es negativo o positivo, más grande es el peso.

Entre más grande sea el peso, más importante es la caracteristica.
'''

'\nMientras más cerca este de cero el coeficiente, mas pequeño es el peso.\nMientras más lejos del cero esté, sin importar si es negativo o positivo, más grande es el peso.\n\nEntre más grande sea el peso, más importante es la caracteristica.\n'

In [53]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [54]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.647455    0.192539
1                 reason_1     2.800197   16.447892
2                 reason_2     0.951884    2.590585
3                 reason_3     3.115553   22.545903
4                 reason_4     0.839001    2.314054
5             Month Values     0.158930    1.172256
6   Transportation Expense     0.605284    1.831773
7                      Age    -0.169891    0.843757
8          Body Mass Index     0.279811    1.322880
9                Education    -0.210533    0.810152
10                Children     0.348262    1.416604
11                    Pets    -0.277396    0.757754

In [55]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 reason_3     3.115553   22.545903
1                 reason_1     2.800197   16.447892
2                 reason_2     0.951884    2.590585
4                 reason_4     0.839001    2.314054
6   Transportation Expense     0.605284    1.831773
10                Children     0.348262    1.416604
8          Body Mass Index     0.279811    1.322880
5             Month Values     0.158930    1.172256
7                      Age    -0.169891    0.843757
9                Education    -0.210533    0.810152
11                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539